---
title: "Project Team"
---

The Western Boreal Initiative is a collaborative co-production between multiple government agencies, university researchers, and indigenous groups.

## Project Leads

- Samuel Hache (ECCC-CWS)
- Mathieu Leblond (ECCC-CWS)
- Junior Tremblay (ECCC-CWS)
- Eliot McIntire (NRCAN-CFS)
- Tati Micheletti (UBC)

## Funding

- NRCAN-CFS
- ECCC-CWS
- ECCC-STB

## Implementation Team

- Ceres Barros (UBC)
- Celine Boisvenue (NRCAN-CFS)
- Alex Chubaty (FOR-CAST Research & Analytics)
- Steve Cumming (ULaval)
- Ian Eddy (NRCAN-CFS)
- Josie Hughes (ECCC-STB)
- Isolde Lane-Shaw (ULaval)
- Eliot McIntire (NRCAN-CFS)
- Tati Micheletti (UBC)
- Greg Paradis (UBC)
- Ana Raymudo (ULaval)
- Jackie Saturno (Dalhousie)
- Alana Westwood (Dalhousie)
- Dene Nation

## Advisory Committee

- S. Avery-Gomm
- A. Calvert
- S. Carriere
- K. Clark
- L. Coristine
- A. Cox
- D. Cyr
- A. Dookie
- I. Duclos
- W. Easton
- B. Frei
- Z. Gadallah
- M. Gahbauer
- C. Haas
- S. Hache (ECCC-CWS)
- J. Hodson (GNWT)
- T. Imlay
- B. Laurich
- M. Leblond (ECCC-CWS)
- L. Mahon
- O. Melnyk
- E. Nichol
- A. Norris
- J. Olesenski
- J. Polfus
- E. Reed
- J. Schroeder
- L. Smith
- R. Steenweg
- B. Stewart
- D. Stralberg
- C. Toth
- J. Tremblay (ECCC-CWS)
- S. Van Wilgenburg
