name: 'Deploy static content to WBI server'
# see Deployment.R file for notes

on:
  push:
    branches: [ "master" ]
    paths: [ "docs/**"]
  pull_request:
    branches: [ "master" ]
    paths: [ "docs/**"]

jobs:
  deploy-with-webhook:
    name: Deploy static content
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
    - name: 'Trigger deploy webhook'
      run: |
        response=$(curl "http://wbi.predictiveecology.org:9000/hooks/deploy?token=${{secrets.WEBHOOK_SECRET}}")
        echo $response
        [[ $response == "Deploying content" ]] || { exit 1; }
